package com.zurdus.nqueens.ui.theme

import androidx.compose.ui.graphics.Color

internal val RoyalViolet = Color(0xFF5B3CC4)
internal val OnRoyalViolet = Color(0xFFFFFFFF)
internal val RoyalVioletContainer = Color(0xFFE7DEFF)
internal val OnRoyalVioletContainer = Color(0xFF1D1A20)
internal val BurnishedGold = Color(0xFF7B5800)
internal val OnBurnishedGold = Color(0xFFFFFFFF)
internal val BurnishedGoldContainer = Color(0xFFFFDEA1)
internal val OnBurnishedGoldContainer = Color(0xFF1D1A20)
internal val PuzzleTeal = Color(0xFF006B5D)
internal val OnPuzzleTeal = Color(0xFFFFFFFF)
internal val PuzzleTealContainer = Color(0xFF78F8DB)
internal val OnPuzzleTealContainer = Color(0xFF1D1A20)
internal val WarmBackground = Color(0xFFFCF8FF)
internal val WarmSurfaceContainer = Color(0xFFF1ECF5)
internal val WarmSurfaceContainerHighest = Color(0xFFE7E1EB)
internal val Ink = Color(0xFF1D1A20)
internal val InkVariant = Color(0xFF49454E)
internal val Outline = Color(0xFF7A757F)
internal val OutlineVariant = Color(0xFFCAC4D0)
internal val Error = Color(0xFFBA1A1A)
internal val ErrorContainer = Color(0xFFFFDAD6)

internal val DarkRoyalViolet = Color(0xFFCDBDFF)
internal val OnDarkRoyalViolet = Color(0xFF2D006C)
internal val DarkRoyalVioletContainer = Color(0xFF43209E)
internal val OnDarkRoyalVioletContainer = Color(0xFFE7DEFF)
internal val DarkBurnishedGold = Color(0xFFEBC36D)
internal val OnDarkBurnishedGold = Color(0xFF412D00)
internal val DarkBurnishedGoldContainer = Color(0xFF5D4200)
internal val OnDarkBurnishedGoldContainer = Color(0xFFFFDEA1)
internal val DarkPuzzleTeal = Color(0xFF5EDBC1)
internal val OnDarkPuzzleTeal = Color(0xFF00382F)
internal val DarkPuzzleTealContainer = Color(0xFF005145)
internal val OnDarkPuzzleTealContainer = Color(0xFF78F8DB)
internal val DarkBackground = Color(0xFF151218)
internal val DarkSurfaceContainer = Color(0xFF211E24)
internal val DarkSurfaceContainerHighest = Color(0xFF363139)
internal val DarkInk = Color(0xFFE9E1EB)
internal val DarkInkVariant = Color(0xFFCEC5D0)
internal val DarkOutline = Color(0xFF978F99)
internal val DarkOutlineVariant = Color(0xFF4A454D)
internal val DarkError = Color(0xFFFFB4AB)
internal val OnDarkError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val OnDarkErrorContainer = Color(0xFFFFDAD6)

internal val LightBoardSquare = Color(0xFFF0E4CF)
internal val DarkBoardSquare = Color(0xFF5B447B)
internal val LightBoardSquareInDarkTheme = Color(0xFF8A7C68)
internal val DarkBoardSquareInDarkTheme = Color(0xFF4E3967)
